config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    root 'events#index'

    resources :events do
      resources :comments, only: [:create, :destroy]
      resources :subscriptions, only: [:create, :destroy]
      resources :photos, only: [:create, :destroy]

      post :show, on: :member
    end
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true

  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  # POST /comments
  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      notify_subscribers(@event, @new_comment)
      redirect_to @event, notice: I18n.t('pages.comments.create.created')
    else
      render 'events/show', alert: I18n.t('pages.comments.create.not_created')
    end
  end


  # DELETE /comments/1
  def destroy
    message = nil
    if current_user_can_edit?(@comment)
      @comment.destroy!
      message = {notice: I18n.t('pages.comments.destroy.destroyed')}
    else
      message = {alert: I18n.t('pages.comments.destroy.not_destroyed')}
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end

  def notify_subscribers(event, comment)
    # собираем всех подписчиков и автора события в массив мэйлов, исключаем повторяющиеся
    comment_email = comment.user.email if comment.user.present?
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email]).uniq - [comment_email]

    # XXX: Этот метод может выполняться долго из-за большого числа подписчиков
    # поэтому в реальных приложениях такие вещи надо выносить в background задачи!
    all_emails.each do |mail|
      EventMailer.comment(event, comment, mail).deliver_now
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom bg-dark rounded p-3 text-light">
  <p><%= comment.body %></p>
  <p>
    <small>
      <span class="comment">
        <% if comment.user.present? %>
          <%= render partial: 'users/user', object: comment.user %>
        <% else %>
          <em><strong><%= comment.user_name %></strong></em>
        <% end %>
      </span>
      <em><%= l comment.created_at, format: :short %></em>
      <% if current_user_can_edit?(comment) %>
          <%= link_to(fa_icon('trash'), event_comment_path(comment.event, comment),
                  method: :delete,
                  data: { title: ' ',
                          confirm: t('pages.comments.confirm.consent'),
                          commit: t('global.confirm.ok'),
                          cancel: t('global.confirm.cancel') }
              ) %>
      <% end %>
    </small>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@event, comment] do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: comment} %>

    <% unless user_signed_in? %>
        <div class="form-group">
          <%= f.text_field :user_name, class: 'form-control', placeholder: t('global.forms.placeholder.name') %>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.text_area :body, class: 'form-control', placeholder: t('global.forms.placeholder.body_comment') %>
    </div>

    <div class="actions">
      <%= f.submit t('global.forms.save'), class: 'btn btn-dark' %>
    </div>
<% end %>